---
- name: Install PostgreSQL 14
  hosts: db
  become: yes

  tasks:
    - name: Install postgresql
      apt:
        name: postgresql-14
        update_cache: yes

    - name: allow what IP address(es) to listen on;
      shell: sed -i "s/^#listen_addresses = 'localhost'/listen_addresses = '*'" /etc/postgresql/14/main/postgresql.conf
    
    - name: allows authentication for all users connecting to all databases from any IPv4 address (0.0.0.0/0)
      shell: sed -i '$a host    all             all             0.0.0.0/0         md5' /etc/postgresql/14/main/pg_hba.conf 
    
    - name: restart postgresql
      shell: systemctl restart postgresql 
