---
- name: Install PostgreSQL 14
  hosts: db
  become: yes

  tasks:
    - name: Install postgresql
      apt:
        name: postgresql-14
        update_cache: yes

    - name: allow what IP address(es) to listen on;
      shell: sed -i "s/^#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/14/main/postgresql.conf
    
    - name: allows authentication for all users connecting to all databases from any IPv4 address (0.0.0.0/0)
      shell: sed -i '$a host    all             all             0.0.0.0/0         md5' /etc/postgresql/14/main/pg_hba.conf 
    
    - name: restart postgresql
      shell: systemctl restart postgresql 

    - name: drop db
      #shell: sudo -i -u postgres psql -c "DROP DATABASE {{ db_name }};"
      
    - name: drop user
      #shell: sudo -i -u postgres psql -c "DROP USER {{ db_user }};"
      
    
    - name: create db
      shell: sudo -i -u postgres psql -c "CREATE DATABASE {{ db_name }};"
  
    - name: create user/password
      shell: sudo -i -u postgres psql -c "CREATE USER {{ db_user }} WITH ENCRYPTED PASSWORD '{{ db_pass }}';"
  
    - name: put rights on database
      shell: sudo -i -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ db_name }} TO {{ db_user }};"
  
    
