---
- name: Install and configure nginx
  hosts: lb
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
  
    - name: Copy Nginx configuration file
      template:
        src: templates/lb_nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        #owner: root
        #group: root
        #mode: '0644'
      notify: Reload Nginx
  
  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      
      
