---
- name: Install and configure nginx + postgresql client
  hosts: web
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    
    - name: Copy Nginx configuration file
      template:
        src: templates/web_nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        #owner: root
        #group: root
        #mode: '0644'
      notify: Reload Nginx
  
    - name: Install postgresql client
      apt:
        name: postgresql-client-14
        state: present        
    
    - name: Copy frontend build
      copy:
        src: ../week1/rhnatyshyn/flask
        dest: .
    
    - name: Copy .env
      template:
        src: templates/.env.j2
        dest: flask
        
    
    - name: Preconfigure and run Flask app
      shell: |
        cd flask
        sudo apt install python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools -y
        sudo apt install python3-venv -y
        python3 -m venv flasktest
        source flasktest/bin/activate 
        pip install -r requirements.txt
        pip install flask flask_login flask_sqlalchemy flask_migrate psycopg2-binary gunicorn
      args:
        executable: /bin/bash

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
