# This workfrow includes the next listers and formaters check:
# Pylint - for .py files
# ShellCheck - for .sh files
# Prettier

name: Linters and Formatters

on:
    push: #all branches

    workflow_dispatch:

defaults:
  run:
    working-directory: ./week1

jobs:
    Pylint: #for pylint used solution from marketplace 
        name: Pylint
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                 python -m pip install --upgrade pip
                 pip install -r ./rhnatyshyn/flask/requirements.txt
                 pip install pylint

            - name: Run Pylint
              run: pylint ./.rhnatyshyn/flask/birdproject/*.py --fail-under=6.0
    
    shellCheck:
        name: ShellCheck
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            
            - name: Run ShellCheck
              uses: ludeeus/action-shellcheck@master  
              with:
                check_together: 'yes'
                severity: error     #only report when the issue is error
                format: gcc         #has single-line log messages
              env:
                SHELLCHECK_OPTS: -s bash  #test against bash shell
    
    prettier:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: '18'
            
            - name: Install Prettier
              run: npm install prettier

            - name: Run Prettier and make changes
              run:  npx prettier . --check  #will display only files that are not formated, not to change them --write